on: [push, pull_request]

name: Yarn Build

jobs:
  check:
    name: Yarn Build smoke test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
